@host = localhost:8080

POST http://{{host}}/room/create

###
GET http://{{host}}/room/0

###
POST http://{{host}}/room/0/action

((time 1) (action (AddBody (id 0) (x0 600) (y0 100) (r 100) (mu 2) (m 10))) (timeout ()))